---
- name: show return value of command module
  hosts: all
  gather_facts: False
  tasks:
    - name: capture output of id command
      command: id -un
      register: login
    - debug: var=login
    - debug: msg="Logged in as user {{ login.stdout }}"
