- name: making changes to localhost
  hosts: 127.0.0.1
  connection: local
  become: yes
  become_user: root
  tasks:
  - name: Collecting local date in a variable
    debug:
      var=ansible_date_time.date
  - name: creating directory inside /home/apache/patch_logs folder if missing
    file:
      path: /home/apache/patch_logs/{{ansible_date_time.date}}
      state: directory
      owner: apache
      group: apache
      mode: "u=rwx,g=rw,o=rw"

- name: executing these commands on remote host
  hosts: group1 ,!127.0.0.1
  become: yes
  become_user: root
  tasks:
  - name: updating Patches with ksplice
    shell: uptrack-upgrade -y > /tmp/{{ansible_hostname}}.applyPatchlog.out
  - name: feching log file and copying to website
    fetch:
      src: /tmp/{{ ansible_hostname }}.applyPatchlog.out
      dest: /tmp/
      flat: true
- name: making changes to localhost
  hosts: 127.0.0.1
  connection: local
  become: yes
  become_user: root
  tasks:
  - name: moving log file from /tmp/ to website
    shell: cp /tmp/*.applyPatchlog.out /home/apache/patch_logs/{{ansible_date_time.date}}/
  - name: setting permission to apache user
    shell: chown apache:apache /home/apache/patch_logs/{{ansible_date_time.date}}/*
    args:
      warn: false
