---
- name: Gather facts for partitions
  gather_facts: True
  hosts: all
  become: True
  tasks:
    - name: setup
      setup:
      register: factone

    - set_fact:
        all_devices: "{{ factone.ansible_facts.ansible_devices }}"

    - name: Return data for devices where partitions are defined
      debug:
        msg: "{{ item.key }}"
      with_dict: "{{ all_devices }}"
      when: item.value.partitions
